
import Head from "next/head";

export default function Home() {
  return (
  <><Head>
      <title>portfolio</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="favicon/favicon.ico" />
    </Head>
    
    <main >
    <div className="card bg-dark text-white">
  <img src="image/Coverr.jpg" className="card-img opacity-75" alt="..."/>
  <div className="card-img-overlay d-flex flex-column justify-content-center align-items-center">
    <h5 className="card-title h1">Card title</h5>
    <p className="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
    <button type="button" className="btn btn-outline-light">Secondary</button>
  </div>
</div>



<div id="carouselExampleInterval" className="carousel slide mt-5" data-ride="carousel">
  <div className="carousel-inner">

    <div className="carousel-item active d-flex flex-row" data-interval="10000">
    <div className="card border-0 me-5" >
  <img src="image/CardImage1.jpg" className="card-img-top" alt="..."/>
  <div className="card-body">
    <h5 className="card-title">Card title</h5>
    <p className="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
  </div>
</div>

<div className="card border-0 mx-3" >
  <img src="image/CardImage1.jpg" className="card-img-top" alt="..."/>
  <div className="card-body">
    <h5 className="card-title">Card title</h5>
    <p className="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
  </div>
</div>

<div className="card border-0 ms-5" >
  <img src="image/CardImage1.jpg" className="card-img-top" alt="..."/>
  <div className="card-body">
    <h5 className="card-title">Card title</h5>
    <p className="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
  </div>
</div>
</div>

 
    <div className="carousel-item" data-interval="2000">
      
    </div>
    <div className="carousel-item">
      
    </div>
  </div>
  <a className="carousel-control-prev" href="#carouselExampleInterval" role="button" data-slide="prev">
    <span className="carousel-control-prev-icon" aria-hidden="true"></span>
    <span className="sr-only">Previous</span>
  </a>
  <a className="carousel-control-next" href="#carouselExampleInterval" role="button" data-slide="next">
    <span className="carousel-control-next-icon" aria-hidden="true"></span>
    <span className="sr-only">Next</span>
  </a>
</div>



      </main></>
  )
}
